version: '3.6'

services:
  academy-webapp:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - VUE_APP_BASE_API=${VUE_APP_BASE_API}
      - VUE_APP_PARENT_DOMAIN=${VUE_APP_PARENT_DOMAIN}
    ports:
      - 80:80