name: Build Weni Academy Frontend (Connect) in Shared (Push Branch Develop)

on:
  push:
    branches:
      - build
      - develop

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Set variables
        run: |
          echo "COMMIT_SHA=${GITHUB_SHA}" >> ${GITHUB_ENV}
          echo "COMMIT_SHA=${GITHUB_SHA}"
          export TAG="front-${GITHUB_SHA::7}" 
          # TAG=$(echo $GITHUB_REF | cut -d"/" -f3) 
          echo "TAG=${TAG}" >> $GITHUB_ENV
          echo "TAG=${TAG}"
          VERSION=${TAG}
          echo "VERSION=${VERSION}" >> ${GITHUB_ENV}
          echo "VERSION=${VERSION}"
          echo "REGISTRY_URL=869898323958.dkr.ecr.us-east-1.amazonaws.com" >> ${GITHUB_ENV}
          echo "REGISTRY_URL=869898323958.dkr.ecr.us-east-1.amazonaws.com"
          echo "IMAGE_TAG=weni-academy:${TAG}" >> ${GITHUB_ENV}
          echo "IMAGE_TAG=weni-academy:${TAG}"
          echo "IMAGE_REPOSITORY=Ilhasoft/weni-academy" >> ${GITHUB_ENV}
          echo "IMAGE_REPOSITORY=Ilhasoft/weni-academy"
          echo "MANIFESTS_REPOSITORY=Ilhasoft/kubernetes-manifests-connect" >> ${GITHUB_ENV}
          echo "MANIFESTS_REPOSITORY=Ilhasoft/kubernetes-manifests-connect"
          echo "PROJECT_DIR=academy-front" >> ${GITHUB_ENV}
          echo "PROJECT_DIR=academy-front"
          echo "PATCH_TARGET=deployment.json" >> ${GITHUB_ENV}
          echo "PATCH_TARGET=deployment.json"
          
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to ECR
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY_URL }}
          username: ${{ secrets.AWS_ACCESS_KEY_ID_SHARED }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY_SHARED }}

      - name: Build and push - Weni Academy Frontend Image
        id: docker_build1
        uses: docker/build-push-action@v2
        with:
          context: .
          labels: branch=develop,commit=${{env.COMMIT_SHA}},repository=https://github.com/${{env.IMAGE_REPOSITORY}}
          file: Dockerfile
          push: true
          tags: ${{env.REGISTRY_URL}}/${{env.IMAGE_TAG}}
          no-cache: true
          
      - name: Check out Kubernetes Manifests
        uses: actions/checkout@master
        with:
          ref: main
          repository: ${{ env.MANIFESTS_REPOSITORY }}
          token: ${{ secrets.DEVOPS_GITHUB_PERMANENT_TOKEN }}
          path: ./kubernetes-manifests/  
      
      - name: Update image on deployment
        run: |
          echo 'New configurations:'
          new_configuration=$(
            cat "./kubernetes-manifests/${{env.PROJECT_DIR}}/develop/${{env.PATCH_TARGET}}" \
              | jq '(..|select(.path == "/spec/template/spec/containers/0/image")?) += {value: "'"${{env.REGISTRY_URL}}/${{env.IMAGE_TAG}}"'"}'
          )
          echo "${new_configuration}"
          echo "${new_configuration}" > "./kubernetes-manifests/${{env.PROJECT_DIR}}/develop/${{env.PATCH_TARGET}}"
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.DEVOPS_GITHUB_PERMANENT_TOKEN }}
          repository: ${{ env.MANIFESTS_REPOSITORY }}        
          directory: ./kubernetes-manifests/
          branch: main
          message: "From Weni Academy Frontend Build (Push Branch Develop)" 
          